init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.5.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

image: 
  - Visual Studio 2019
  - Ubuntu1804

configuration: Release

environment:
  LMVTestAgentUsername: SecretAgentTest Resident
  LMVTestAgentPassword:
    secure: bOoXrGfLiHjZlCG1tJ+nDQ==

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

build:
  project: LibreMetaverse.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

  matrix:
    - image: Visual Studio 2019
      target_frameworks: 'netstandard2.0;net471'
    - image: Ubuntu1804
      target_frameworks: 'netstandard2.0'

before_build:
  - nuget restore LibreMetaverse.sln

matrix:
  allow_failures:
    - image: Ubuntu1804

for:
- 
  matrix:
    only:
      - image: Visual Studio 2019

  deploy:
    - provider: NuGet
      name: nuget_release
      api_key:
        secure: WAEp9wQu4tWKiMdcfog7FWpzk7rPou8flMCYlmYy3mZ+thKwmG1ht4o4mmEE6ZLs
      skip_symbols: true
      artifact: /.*LibreMetaverse.*\.nupkg/
