init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v1.8.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
  - job_name: Windows Build
    platform: x64
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Release
  - job_name: Linux Build
    platform: x64
    appveyor_build_worker_image: Ubuntu2004
    configuration: ReleaseNoGui
  - job_name: MacOS Build
    platform: x64
    appveyor_build_worker_image: macos-mojave
    configuration: ReleaseNoGui

  LMVTestAgentUsername: SecretAgentTest Resident
  LMVTestAgentPassword:
    secure: bOoXrGfLiHjZlCG1tJ+nDQ==
  PfxDownloadUrl:
    secure: 6zETilPjqhwgznp0rOyu2lloNy/uIU0coJBWCW+ADBiofQTU8ZuU3BCIEifEPI1R
  PfxDownloadPasswd:
    secure: qzHJldnavMFT8+Cm2eXndg==
  PfxPassword:
    secure: +vWSGzLkiBGVIxfPb+iRtD+/maQjI2d92hN4PoNAxMc=

pull_requests:
  do_not_increment_build_number: false

nuget:
  disable_publish_on_pr: true

build:
  project: LibreMetaverse.sln
  parallel: true
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
  - ps: util/InstallRemotePfx.ps1 -PfxDownloadUrl $env:PfxDownloadUrl -PfxDownloadUser AppVeyor -PfxDownloadPasswd $env:PfxDownloadPasswd -PfxPasswd $env:PfxPassword
  - nuget restore LibreMetaverse.sln

after_build:
  - ps: if ($isWindows) { nuget sign LibreMetaverse.$env:TAG_VERSION.nupkg -CertificateFingerprint 95AEDF70A4C4E6184F43CA8C1E17B6D838430184 -CertificatePassword $env:PfxPassword -Timestamper http://timestamp.comodoca.com }
  - ps: if ($isWindows) { Get-ChildItem -Filter "*.nupkg" -Path "C:\Users\appveyor\AppData\Local\Temp\" -recurse | Compress-Archive -DestinationPath "nuget_libraries.zip" -Verbose }

artifacts:
  - path: 'LibreMetaverse.*.nupkg'
    name: 'LibreMetaverse pkg'
    type: Auto
  - path: 'nuget_libraries.zip'
    name: 'Nuget Library Archive'
    type: Auto
