version: 1.0.0.{build}

image: Visual Studio 2015

configuration: Release

build:
  parallel: true
  verbosity: minimal

before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  
build_script:
  - runprebuild2015.bat msbuild docs dist
