swagger: '2.0'
info:
  version: 0.0.0
  title: 'Linden Lab Official:Inventory API v3'
paths:
  '/category/{category}':
    get:
      description: Retrieve a category
      parameters:
        - name: category
          in: path
          description: 'Category UUID or ''special'' category name, e.g. "current"'
          required: true
          type: string
          format: double
        - name: tid
          in: query
          description: Transaction ID
          required: false
          type: string
        - name: depth
          in: query
          description: Category child depth to retrieve
          required: false
          type: number
        - name: simulate
          in: query
          description: Whether or not to skip writing back results
          required: false
          type: boolean
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/categoryResponse'
        '304':
          description: Not modified
        '404':
          description: Category not found
          schema:
            $ref: '#/definitions/errorCategoryNotFound'
        '412':
          description: Precondition failed
          schema:
            $ref: '#/definitions/errorPreconditionFailed'
definitions:
  categoryResponse:
    type: object
    properties:
      xxx:
        type: string
  categoryChildResponse:
    type: object
    properties:
      xxx:
        type: string
  errorCategoryNotFound:
    type: object
    properties:
      error_line_number:
        type: integer
      error_filename:
        type: string
      error_description:
        type: string
      error_function:
        type: string
      category_id:
        type: string
      error_code:
        type: integer
  errorPreconditionFailed:
    type: object
    properties:
      error_line_number:
        type: integer
      error_filename:
        type: string
      error_description:
        type: string
      error_function:
        type: string
      etags:
        type: array
        items:
          type: string
      etag:
        type: string
      error_code:
        type: integer
      condition:
        type: string
