# A test workflow, which seems to get good results sometimes.
# (gwyneth 20220418)
# See https://docs.microsoft.com/en-us/dotnet/devops/dotnet-test-github-action
name: .NET

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:

    name: dotnet-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore LibreMetaverse.ReleaseNoGui.sln
    - name: Build
      run: dotnet build --no-restore LibreMetaverse.ReleaseNoGui.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal LibreMetaverse.ReleaseNoGui.sln
